cloudprovider: elemental

cloudCredentialSecretName: ""

rancher:
  cattle:
    url: rancher.kube.lol

cluster:
  name: elemental-harbor-cluster
  labels:
    type: elemental
    cluster: elemental-harbor
  config:
    systemDefaultRegistry: rgcrprod.azurecr.us
    kubernetesVersion: v1.27.12+rke2r1
    localClusterAuthEndpoint:
      enabled: false
    additionalManifests: |-
      ---
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-ingress-nginx
        namespace: kube-system
      spec:
        valuesContent: |-
          controller:
            service:
              enabled: true
              type: LoadBalancer
    cni: canal
    docker: false
    disable_kube_proxy: false
    etcd_expose_metrics: false
    enableNetworkPolicy: true
    # defaultClusterRoleForProjectMembers: ''
    # defaultPodSecurityAdmissionConfigurationTemplateName: ''
    # defaultPodSecurityPolicyTemplateName: ''
    profile: '' # cis-1.6, cis-1.23
    selinux: false
    secrets_encryption: false
    write_kubeconfig_mode: 0600
    use_service_account_credentials: false
    protect_kernel_defaults: false
    cloud_provider_name: '' # https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers
    # cloud_provider_config: '' # cloud provider config secret here (example: secret://fleet-default:cloudprovider)
    # kube_controller_manager_arg:
      # - kube controller manager arguments here (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager)
    # kube_scheduler_arg:
      # - kube scheduler arguments here (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler)
    # kube_apiserver_arg:
      # - kube apiserver arguments here (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver)
    # kubelet_arg:
      # - kubelet arguments here (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet)
    registries:
      enabled: true
      configs:
        - name: rgcrprod.azurecr.us
          authConfigSecretName: registryconfig-auth-t95qm  # Update to your secret for your registry
          caBundle: ''
          insecureSkipVerify: false

    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false

# node and nodepool(s) values
nodepools:
  - name: elemental-harbor-main
    quantity: 3
    etcd: true
    controlplane: true
    worker: true
    paused: false
    selector:
      matchLabels:
        new-cluster: enabled # Update this to match your Elemental machine labels